set deno-dev basic ubuntu image to focal
AGhost-7/docker-dev pull request #77
Opened 2020-12-13 22:58 UTC by hardy613

- update build.py with deno-dev base image to focal

2020-12-14 06:18 UTC, AGhost-7 commented on build.py
> +    {'name': 'redis-dev', 'tag': '6', 'path': 'redis'}
I moved the folder in the correct location instead. It doesn't need the path specified anymore.

2020-12-14 06:29 UTC, AGhost-7 requested changes
Are you sure this works? Auto-complete seems broken among other things.

2020-12-14 17:23 UTC, hardy613 commented
> Are you sure this works? Auto-complete seems broken among other things.

No. should have been set to draft. Apologies. 

Autocomplete might be related to recent deno updates - might need to generate deno types. Also, deno is in rapid development and new releases happen often, what would be the best way to manage a fast-paced environment like deno?

2020-12-14 18:01 UTC, AGhost-7 commented
> Autocomplete might be related to recent deno updates - might need to generate deno types
I get a YCM error when I try to run `:YcmCompleter GoTo` in neovim.

> Also, deno is in rapid development and new releases happen often, what would be the best way to manage a fast-paced environment like deno?
For Rust I just used different channels (one for nightly and one for stable). Is there something similar for deno?

2020-12-15 06:50 UTC, hardy613 commented
YCM seems to have a hard time installing still and the error gets mangled by installing the NVIM Plugs

2020-12-17 20:19 UTC, AGhost-7 commented
@hardy613 Try installing manually in that case. You can start a container up using your base image (`aghost7/nvim:focal`) and run your script line by line.

2020-12-21 00:47 UTC, hardy613 commented
`:YcmCompleter GoTo` working

![Screenshot from 2020-12-20 19-46-14](https://user-images.githubusercontent.com/6975844/102728848-0b143e80-42fc-11eb-84e3-312f78c6522d.png)

with nice property hints

![Screenshot from 2020-12-20 19-45-23](https://user-images.githubusercontent.com/6975844/102728849-0bacd500-42fc-11eb-8655-02dc8758b2d9.png)

2020-12-21 22:41 UTC, AGhost-7 approved these changes

2020-12-21 22:41 UTC, merged